insert into songs (Title, Artist, Genre) values ('Bassline Bounce', 'Ava Hernandez', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Hip Hop Beats', 'John Smith', 'Rock');
insert into songs (Title, Artist, Genre) values ('Melancholy Melodies', 'Olivia Martinez', 'Rock');
insert into songs (Title, Artist, Genre) values ('Guitar Legends', 'Sophia Wilson', 'Folk');
insert into songs (Title, Artist, Genre) values ('Gospel Hymns', 'James Garcia', 'Pop');
insert into songs (Title, Artist, Genre) values ('Drumming Delight', 'Olivia Martinez', 'Country');
insert into songs (Title, Artist, Genre) values ('Classical Serenade', 'David Anderson', 'Country');
insert into songs (Title, Artist, Genre) values ('Acoustic Serenity', 'Ava Hernandez', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Electrifying Energy', 'John Smith', 'Rock');
insert into songs (Title, Artist, Genre) values ('R&B Soul', 'Daniel Thompson', 'Pop');
insert into songs (Title, Artist, Genre) values ('Electronic Escapade', 'James Garcia', 'Rock');
insert into songs (Title, Artist, Genre) values ('Melodies of Joy', 'John Smith', 'Country');
insert into songs (Title, Artist, Genre) values ('Symphony of Dreams', 'Ava Hernandez', 'Country');
insert into songs (Title, Artist, Genre) values ('Melodies of Joy', 'John Smith', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Techno Thrills', 'David Anderson', 'Classical');
insert into songs (Title, Artist, Genre) values ('Metal Mayhem', 'Daniel Thompson', 'Pop');
insert into songs (Title, Artist, Genre) values ('Indie Melodies', 'Emma Taylor', 'Rock');
insert into songs (Title, Artist, Genre) values ('Opera Extravaganza', 'John Smith', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Serenade of Love', 'John Smith', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Latin Fusion', 'Michael Davis', 'Pop');
insert into songs (Title, Artist, Genre) values ('Reggae Vibes', 'Emily Johnson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Choral Harmony', 'James Garcia', 'Pop');
insert into songs (Title, Artist, Genre) values ('Funky Grooves', 'Emma Taylor', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Hip Hop Beats', 'Olivia Martinez', 'Rock');
insert into songs (Title, Artist, Genre) values ('Bassline Bounce', 'Emily Johnson', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Melodies of Joy', 'Michael Davis', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Acoustic Serenity', 'Michael Davis', 'Folk');
insert into songs (Title, Artist, Genre) values ('Serenade of Love', 'Michael Davis', 'R&B');
insert into songs (Title, Artist, Genre) values ('Harmony in Motion', 'David Anderson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Disco Fever', 'Olivia Martinez', 'Country');
insert into songs (Title, Artist, Genre) values ('Indie Melodies', 'David Anderson', 'Electronic');
insert into songs (Title, Artist, Genre) values ('Bluesy Tunes', 'Michael Davis', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Electrifying Energy', 'Daniel Thompson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Serenade of Love', 'James Garcia', 'Folk');
insert into songs (Title, Artist, Genre) values ('Pop Sensation', 'Sophia Wilson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Folk Tales', 'James Garcia', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Funky Grooves', 'Sophia Wilson', 'Rock');
insert into songs (Title, Artist, Genre) values ('Piano Sonata', 'Ava Hernandez', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Folk Tales', 'Olivia Martinez', 'Folk');
insert into songs (Title, Artist, Genre) values ('Choral Harmony', 'Ava Hernandez', 'Country');
insert into songs (Title, Artist, Genre) values ('Latin Fusion', 'Emma Taylor', 'Folk');
insert into songs (Title, Artist, Genre) values ('Bassline Bounce', 'James Garcia', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Electronic Escapade', 'Sophia Wilson', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Alternative Rhythms', 'Emma Taylor', 'Reggae');
insert into songs (Title, Artist, Genre) values ('Funky Grooves', 'Ava Hernandez', 'Pop');
insert into songs (Title, Artist, Genre) values ('Rocking the Night Away', 'David Anderson', 'Jazz');
insert into songs (Title, Artist, Genre) values ('Country Roads', 'John Smith', 'Hip Hop');
insert into songs (Title, Artist, Genre) values ('Opera Extravaganza', 'Ava Hernandez', 'Folk');
insert into songs (Title, Artist, Genre) values ('Echoes of Eternity', 'Daniel Thompson', 'Country');
insert into songs (Title, Artist, Genre) values ('Choral Harmony', 'David Anderson', 'Jazz');
